//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lp.Suscriptor.Seguridad.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acceso
    {
        public int IdUsuario { get; set; }
        public long IdAcceso { get; set; }
        public string HostAdress { get; set; }
        public string HostName { get; set; }
        public string Agente { get; set; }
        public string Token { get; set; }
        public bool TokenHabilitado { get; set; }
        public System.DateTime TokenFechaExp { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
