//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoError
    {
        public string Id { get; set; }
        public string Usuario { get; set; }
        public string HostAdress { get; set; }
        public string HostName { get; set; }
        public string Agente { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Pila { get; set; }
        public string Excepcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
