//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoError
    {
        public string Id { get; set; }
        public string Usuario { get; set; }
        public string HostAdress { get; set; }
        public string HostName { get; set; }
        public string Agente { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Pila { get; set; }
        public string Excepcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
