//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public Aplicacion()
        {
            this.Bitacora = new HashSet<Bitacora>();
        }
    
        public int IdAplicacion { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public bool HabilitarBitacoraResp { get; set; }
        public bool HabilitarBitacoraReq { get; set; }
        public bool HabilitarBitacoraEx { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Bitacora> Bitacora { get; set; }
    }
}
