//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public Aplicacion()
        {
            this.Bitacora = new HashSet<Bitacora>();
        }
    
        public int IdAplicacion { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public bool HabilitarBitacoraResp { get; set; }
        public bool HabilitarBitacoraReq { get; set; }
        public bool HabilitarBitacoraEx { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Bitacora> Bitacora { get; set; }
    }
}
