//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long IdBitacora { get; set; }
        public Nullable<int> IdFuncion { get; set; }
        public byte IdTipoBitacora { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Pila { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Acceso Acceso { get; set; }
        public virtual Aplicacion Aplicacion { get; set; }
    }
}
