//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public Nullable<long> IdBitacora { get; set; }
        public int IdUsuario { get; set; }
        public long IdAcceso { get; set; }
        public int IdAplicacion { get; set; }
        public Nullable<int> IdFuncion { get; set; }
        public byte IdTipoBitacora { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Pila { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Acceso Acceso { get; set; }
        public virtual Aplicacion Aplicacion { get; set; }
    }
}
