//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int IdUsuario { get; set; }
        public byte IdRol { get; set; }
        public int IdArea { get; set; }
        public int IdHistorico { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaIniVig { get; set; }
        public Nullable<System.DateTime> FechaFinVig { get; set; }
        public int IdSubArea { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Area Area { get; set; }
    }
}
