//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpeCarEntities : DbContext
    {
        public OpeCarEntities()
            : base("name=OpeCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acceso> Acceso { get; set; }
        public virtual DbSet<Aplicacion> Aplicacion { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioHist> UsuarioHist { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<AreaHist> AreaHist { get; set; }
        public virtual DbSet<AccesoError> AccesoError { get; set; }
        public virtual DbSet<SubArea> SubArea { get; set; }
        public virtual DbSet<SubAreaHist> SubAreaHist { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
    }
}
