//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAreaHist
    {
        public int IdSubArea { get; set; }
        public int IdHistorial { get; set; }
        public string Descripcion { get; set; }
        public bool EsUltimo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool IndicadorHabilitado { get; set; }
    
        public virtual SubArea SubArea { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
