//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubArea
    {
        public SubArea()
        {
            this.SubArea1 = new HashSet<SubArea>();
            this.SubAreaHist = new HashSet<SubAreaHist>();
        }
    
        public int IdSubArea { get; set; }
        public int IdArea { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<SubArea> SubArea1 { get; set; }
        public virtual SubArea SubArea2 { get; set; }
        public virtual ICollection<SubAreaHist> SubAreaHist { get; set; }
    }
}
