//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Acceso = new HashSet<Acceso>();
            this.Aplicacion = new HashSet<Aplicacion>();
            this.Permiso = new HashSet<Permiso>();
            this.Usuario11 = new HashSet<Usuario>();
            this.UsuarioHist = new HashSet<UsuarioHist>();
            this.Parametro = new HashSet<Parametro>();
            this.AreaHist = new HashSet<AreaHist>();
            this.SubAreaHist = new HashSet<SubAreaHist>();
        }
    
        public int IdUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string NombreCompleto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<bool> IndicadorSistema { get; set; }
    
        public virtual ICollection<Acceso> Acceso { get; set; }
        public virtual ICollection<Aplicacion> Aplicacion { get; set; }
        public virtual ICollection<Permiso> Permiso { get; set; }
        public virtual ICollection<Usuario> Usuario11 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<UsuarioHist> UsuarioHist { get; set; }
        public virtual ICollection<Parametro> Parametro { get; set; }
        public virtual ICollection<AreaHist> AreaHist { get; set; }
        public virtual ICollection<SubAreaHist> SubAreaHist { get; set; }
    }
}
